### ISSUE TITLE
PUD license

### ISSUE THREAD

**Issue by kanayamah** [UniversalDependencies/UD_Polish-PUD#1]
@dan-zeman @alina-wroblewska  ``License.txt`` says that it is ``(CC BY-NC-SA 4.0)``, while in the bottom line there is a link to ``CC BY-SA 4.0``.   I believe ``CC BY-SA`` is correct as other PUDs are.  Could you modify ``License.txt`` appropriately?

**Comment by dan-zeman** [comment]
I am leaving this for Alina to resolve. Ideally we should have a validation script that detects such inconsistencies between LICENSE.txt and the metadata in README. But it would be difficult because the text in LICENSE.txt can vary. That is why we have the machine-readable metadata in README, and it is propagated across the site from there. (Also the [UD 2.4 license](https://lindat.mff.cuni.cz/repository/xmlui/page/licence-UD-2.4?locale-attribute=en) in Lindat says that this treebank is licensed under CC BY-SA 4.0; this information was copied from the README file manually.)

**Comment by alina-wroblewska** [comment]
I corrected the license acronym to CC BY-SA 4.0 in LICENSE.txt in the dev branch.
